services:
  - type: web
    name: jugans-blog
    runtime: docker
    dockerfilePath: ./Dockerfile  # Correct key is dockerfilePath, not dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jugansdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PORT
        value: "8000"  # Tell your app to bind to this port
    healthCheckPath: /
