services:
  - type: web
    name: jugans-blog
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn blog_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jugansdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true