services:
  - type: web
    name: jugans-blog
    runtime: docker  # Changed from python to docker
    dockerfile: Dockerfile  # Point to your Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jugansdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"  # Ensure debug is off in production
    plan: free
    healthCheckPath: /  # Recommended for Docker