# Generated by Django 5.2.1 on 2025-05-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juganstar_blog', '0002_alter_post_slug'),
    ]

    operations = [
    ]
